xpath:
  next_addlink: //*/div/div[2]/h3/a/div/div/div/g-img/img
  imgUrlCrawl: //img[@class="sFlh5c pT0Scc iPVvYb"]

url:
  urlGoogleSearch: https://www.google.com.vn/imghp?hl=vi

css:
  cssScronto: .mye4qd